name: release-version

on:
  workflow_call:
    inputs:
      version: { required: true, type: string }

env:
  REGISTRY: ghcr.io
  SERVER_IMAGE: ${{ github.repository_owner }}/mattermost-team
  MMCTL_IMAGE: ${{ github.repository_owner }}/mattermost-mmctl
  VERSION: ${{ inputs.version }}

jobs:
  prepare:
    permissions: { contents: write }
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
      - run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - uses: extractions/setup-just@v4
      - run: |
          just patch "$VERSION"
          git diff --quiet || git commit -a -m "mattermost $VERSION"
      - run: just release-rc "$VERSION"

  build:
    needs: prepare
    permissions: { contents: read, packages: write }
    strategy:
      fail-fast: false
      matrix:
        target:
          - { runner: ubuntu-24.04, arch: amd64 }
          - { runner: ubuntu-24.04-arm, arch: arm64 }
    runs-on: ${{ matrix.target.runner }}
    env:
      ARCH: ${{ matrix.target.arch }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: v${{ inputs.version }}-rc
          fetch-tags: true
      - uses: extractions/setup-just@v4
      - run: just build "$VERSION" "$ARCH"
      - run: just export-images "$VERSION" "$ARCH" images
      - uses: actions/upload-artifact@v4
        with:
          name: images-${{ inputs.version }}-${{ matrix.target.arch }}
          path: images/
          retention-days: 1
          if-no-files-found: error

  merge:
    needs: build
    permissions: { contents: read, packages: write }
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: images-${{ inputs.version }}-*
          path: images/
          merge-multiple: true
      - run: tree images/
      - env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: just login
      - run: just import-images images
      - run: just assemble "$VERSION"
      - run: just publish-manifests "$VERSION"

  release:
    needs: merge
    permissions: { contents: write, packages: read }
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: v${{ inputs.version }}-rc
          fetch-tags: true
      - run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - uses: extractions/setup-just@v4
      - run: just verify-manifests "$VERSION"
      - run: just release "$VERSION"
